In [1]:
import pymysql
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('movie_crawling.csv',index_col=0)
data

,날짜,평점,장르,국가,상영시간,개봉일,줄거리
0,2020-05-01,9.54점,드라마,"레바논,프랑스",126분,2019.01.24개봉,"나를 세상에 태어나게 한 ""부모님을 고소하고 싶어요...""-출생기록조차 없이 살아온..."
1,2020-05-01,9.30점,"드라마,뮤지컬",미국,104분,"2020.05.21재개봉,2017.12.20개봉","쇼 비즈니스의 창시자이자, 꿈의 무대로 전세계를 매료시킨 남자‘바넘’의 이야기에서 ..."
2,2020-05-01,9.63점,드라마,"중국,홍콩",171분,"2020.05.01재개봉,2017.03.30재개봉,1993.12.24개봉",어렸을 때부터 함께 경극을 해온 ‘두지’(장국영)와 ‘시투’(장풍의). 세상에 둘...
3,2020-05-01,9.28점,드라마,"영국,프랑스,벨기에",100분,2016.12.08개봉,평생을 성실하게 목수로 살아가던 다니엘은 지병인 심장병이 악화되어 일을 계속 해나갈...
4,2020-05-01,8.76점,드라마,프랑스,82분,2020.05.14개봉,"새로 이사 온 아이, ‘미카엘’.파란색을 좋아하고, 끝내주는 축구 실력과 유난히 잘..."
...,...,...,...,...,...,...,...
405,2020-06-10,9.18점,"애니메이션,미스터리","영국,폴란드",107분,"2018.12.13재개봉,2017.11.09개봉",살아생전 단 한 점의 그림만을 팔았던 화가 ‘빈센트’의 죽음 후 1년. 아버지의 부...
406,2020-06-10,9.25점,드라마,일본,121분,2018.07.26개봉,할머니의 연금과 물건을 훔쳐 생활하며 가난하지만 웃음이 끊이지 않는 어느 가족.우연...
407,2020-06-10,9.41점,"애니메이션,가족,드라마,판타지",일본,97분,"2016.01.14재개봉,2014.04.25재개봉,2007.06.14개봉",저 마코토에게는 남들에게 말 못할 비밀이 하나 있어요. 타임리프라고 하는 능력이죠....
408,2020-06-10,9.15점,"드라마,멜로/로맨스",미국,135분,2018.10.09개봉,노래에 놀라운 재능을 가졌지만 외모에는 자신이 없는 무명가수 앨리(레이디 가가)는공...
409,2020-06-10,9.40점,"애니메이션,판타지,멜로/로맨스,드라마,모험,가족",일본,117분,2012.09.13개봉,"평범한 여대생 '하나'는 강의실에서 우연히 만나게 된 '그'에게 반하게 되고, 곧 ..."

In [4]:
def make_DB(password, DB_name):
    conn = pymysql.connect(host='localhost', 
                           user = 'root', 
                           password=password, 
                           charset='utf8',
                           cursorclass=pymysql.cursors.DictCursor)
    try:
        with conn.cursor() as cursor:
            print('creating DataBase ...')
            sql = 'CREATE DATABASE '+ DB_name
            cursor.execute(sql)
        conn.commit()
    finally:
        conn.close()

In [7]:
def make_table(password, DB_name, table_name):
    conn = pymysql.connect(host='localhost', 
                           user = 'root', 
                           password=password, 
                           db=DB_name, 
                           charset='utf8',
                           cursorclass=pymysql.cursors.DictCursor)
    try:
        with conn.cursor() as cursor:
            print('creating table ...')
            # 테이블이 생성되지 않은 경우만 테이블 생성
            sql = 'CREATE TABLE IF NOT EXISTS '+table_name+'''(날짜 CHAR(10) NOT NULL,
                                            평점 CHAR(10) NOT NULL, 
                                            장르 CHAR(50) NOT NULL,
                                            국가 CHAR(10) NOT NULL,
                                            상영시간 CHAR(10) NOT NULL,
                                            개봉일 CHAR(100) NOT NULL,
                                            줄거리 VARCHAR(1000) NOT NULL)'''
            cursor.execute(sql)
        conn.commit()
    finally:
        conn.close()

In [ ]:
# 테이블 내용 전체 삭제 

def drop_table(table_name):
    print('delete table ...')
    sql  = "DROP TABLE IF EXISTS "+ table_name
    curs.execute(sql)

In [10]:
# insert문을 사용해서 데이터 입력
def input_data(DB_name,data):
    
    conn = pymysql.connect(host='localhost', 
                           user = 'root', 
                           password='12345', 
                           db=DB_name, 
                           charset='utf8',
                           cursorclass=pymysql.cursors.DictCursor)
    curs = conn.cursor()
    print('inserting data ...')
   
    # FOR LOOP로 바꿔서 수집한 데이터 테이블에  INSERT하기
    sql = "INSERT INTO movie VALUES (%s, %s, %s, %s, %s,%s,%s)"
    for i in data.index:
        val = tuple(data.loc[i,data.columns])
        curs.execute(sql, val)


    conn.commit()
    conn.close()
    print(curs.rowcount, "record inserted.")

In [8]:
make_table('12345','crawler','movie')

creating table ...

In [11]:
input_data('crawler',data)

inserting data ...
1 record inserted.