In [49]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime

In [56]:
job = []
k = {}
d = []
c = []
month = ['202005','202006']
for m in month:

    url = 'http://www.jobkorea.co.kr/starter/calendar/{}'.format(m)
    params={
        'Sel_Date':m
    }
    resp = requests.get(url)
    soup = BeautifulSoup(resp.text)
    body = soup.find('tbody')
    trs = body.find_all('tr')
    for tr in trs:
        divs = tr.find_all('div',class_='calCont')
        
        for div in divs:   
            span = div.find('span',class_='link start')
            if span == None:
                continue
            day = div.find('strong',class_='day').text
            company = span.find('a').text[2:].strip()
            c.append(company)
            if len(day)==1:
                day = '0'+day
        
            d.append(m[0:4]+'-'+m[4:]+'-'+str(day))
            

#     job.append(k)
    df1 = pd.DataFrame({'회사':c,'날짜':d})
print(df1)

             회사          날짜
0         한신공영㈜  2020-05-01
1            한샘  2020-05-02
2       현대오일뱅크㈜  2020-05-04
3        ㈜코리아센터  2020-05-05
4        SK네트웍스  2020-05-06
5        현대모비스㈜  2020-05-07
6      한국토지주택공사  2020-05-08
7     에이비엘생명보험㈜  2020-05-09
8       ㈜넥슨네트웍스  2020-05-10
9         GS건설㈜  2020-05-11
10  ㈜에스앤아이코퍼레이션  2020-05-12
11       기아자동차㈜  2020-05-13
12        롯데홈쇼핑  2020-05-14
13         대한전선  2020-05-15
14     교촌 에프앤비㈜  2020-05-16
15       현대자동차㈜  2020-05-18
16      CJ제일제당㈜  2020-05-19
17       LS일렉트릭  2020-05-20
18        ㈜대우건설  2020-05-21
19          대상㈜  2020-05-22
20       ㈜한국리서치  2020-05-23
21      CJ제일제당㈜  2020-05-25
22     한국수력원자력㈜  2020-05-26
23       현대자동차㈜  2020-05-27
24       ㈜GS리테일  2020-05-28
25        ㈜대우건설  2020-05-29
26         한화토탈  2020-06-01
27      한국수자원공사  2020-06-02
28     한국지역난방공사  2020-06-03
29       기아자동차㈜  2020-06-04
30       현대자동차㈜  2020-06-05
31     한국수력원자력㈜  2020-06-08
32      한국남동발전㈜  2020-06-10
33       화성도시공사  2020-06-16
34    화성시인재육성재단  2020-06-18
35         오토시스  2020-06-20

In [57]:
df1

             회사          날짜
0         한신공영㈜  2020-05-01
1            한샘  2020-05-02
2       현대오일뱅크㈜  2020-05-04
3        ㈜코리아센터  2020-05-05
4        SK네트웍스  2020-05-06
5        현대모비스㈜  2020-05-07
6      한국토지주택공사  2020-05-08
7     에이비엘생명보험㈜  2020-05-09
8       ㈜넥슨네트웍스  2020-05-10
9         GS건설㈜  2020-05-11
10  ㈜에스앤아이코퍼레이션  2020-05-12
11       기아자동차㈜  2020-05-13
12        롯데홈쇼핑  2020-05-14
13         대한전선  2020-05-15
14     교촌 에프앤비㈜  2020-05-16
15       현대자동차㈜  2020-05-18
16      CJ제일제당㈜  2020-05-19
17       LS일렉트릭  2020-05-20
18        ㈜대우건설  2020-05-21
19          대상㈜  2020-05-22
20       ㈜한국리서치  2020-05-23
21      CJ제일제당㈜  2020-05-25
22     한국수력원자력㈜  2020-05-26
23       현대자동차㈜  2020-05-27
24       ㈜GS리테일  2020-05-28
25        ㈜대우건설  2020-05-29
26         한화토탈  2020-06-01
27      한국수자원공사  2020-06-02
28     한국지역난방공사  2020-06-03
29       기아자동차㈜  2020-06-04
30       현대자동차㈜  2020-06-05
31     한국수력원자력㈜  2020-06-08
32      한국남동발전㈜  2020-06-10
33       화성도시공사  2020-06-16
34    화성시인재육성재단  2020-06-18
35         오토시스  2020-06-20

In [58]:
date_range = (pd.date_range(start='20200501', end=datetime.date.today())).strftime("%Y-%m-%d").tolist()
df2=pd.DataFrame({'날짜':date_range})
df2

            날짜
0   2020-05-01
1   2020-05-02
2   2020-05-03
3   2020-05-04
4   2020-05-05
5   2020-05-06
6   2020-05-07
7   2020-05-08
8   2020-05-09
9   2020-05-10
10  2020-05-11
11  2020-05-12
12  2020-05-13
13  2020-05-14
14  2020-05-15
15  2020-05-16
16  2020-05-17
17  2020-05-18
18  2020-05-19
19  2020-05-20
20  2020-05-21
21  2020-05-22
22  2020-05-23
23  2020-05-24
24  2020-05-25
25  2020-05-26
26  2020-05-27
27  2020-05-28
28  2020-05-29
29  2020-05-30
30  2020-05-31
31  2020-06-01
32  2020-06-02
33  2020-06-03
34  2020-06-04
35  2020-06-05
36  2020-06-06
37  2020-06-07
38  2020-06-08

In [59]:
df_OUTER_JOIN = pd.merge(df1, df2, left_on='날짜', right_on='날짜', how='outer', sort=True)
df_finally = df_OUTER_JOIN.fillna('None')

In [60]:
df_finally

             회사          날짜
0         한신공영㈜  2020-05-01
1            한샘  2020-05-02
2          None  2020-05-03
3       현대오일뱅크㈜  2020-05-04
4        ㈜코리아센터  2020-05-05
5        SK네트웍스  2020-05-06
6        현대모비스㈜  2020-05-07
7      한국토지주택공사  2020-05-08
8     에이비엘생명보험㈜  2020-05-09
9       ㈜넥슨네트웍스  2020-05-10
10        GS건설㈜  2020-05-11
11  ㈜에스앤아이코퍼레이션  2020-05-12
12       기아자동차㈜  2020-05-13
13        롯데홈쇼핑  2020-05-14
14         대한전선  2020-05-15
15     교촌 에프앤비㈜  2020-05-16
16         None  2020-05-17
17       현대자동차㈜  2020-05-18
18      CJ제일제당㈜  2020-05-19
19       LS일렉트릭  2020-05-20
20        ㈜대우건설  2020-05-21
21          대상㈜  2020-05-22
22       ㈜한국리서치  2020-05-23
23         None  2020-05-24
24      CJ제일제당㈜  2020-05-25
25     한국수력원자력㈜  2020-05-26
26       현대자동차㈜  2020-05-27
27       ㈜GS리테일  2020-05-28
28        ㈜대우건설  2020-05-29
29         None  2020-05-30
30         None  2020-05-31
31         한화토탈  2020-06-01
32      한국수자원공사  2020-06-02
33     한국지역난방공사  2020-06-03
34       기아자동차㈜  2020-06-04
35       현대자동차㈜  2020-06-05
36         None  2020-06-06
37         None  2020-06-07
38     한국수력원자력㈜  2020-06-08
39      한국남동발전㈜  2020-06-10
40       화성도시공사  2020-06-16
41    화성시인재육성재단  2020-06-18
42         오토시스  2020-06-20

In [61]:
df_finally.to_excel('채용공고.xlsx')